languageCode  = "en-us"
title         = "E&L Wedding"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = "#banner"
    weight  = 1
  [[menu.nav]]
    name    = "The Day"
    URL     = "#timeline"
    weight  = 2
  [[menu.nav]]
    name    = "The People"
    URL     = "#people"
    weight  = 3
  [[menu.nav]]
    name    = "The Venue"
    URL     = "#venue"
    weight  = 4
  [[menu.nav]]
    name    = "FAQs"
    URL     = "#faqs"
    weight  = 5
